branches:
  only:
    - master
sudo: false
language: node_js
node_js:
- '8'
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules


addons:
  apt:
    packages:
      - xvfb

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - env: NAME="lint"
      script:
        - yarn lint
    - env: NAME="test"
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - yarn install
      script:
        - yarn test
