branches:
  only:
    - master
    - /^release\/.+$/

language: node_js
node_js: '8'
cache: yarn

git:
  depth: 1

addons:
  apt:
    packages:
      - xvfb

matrix:
  include:
    - env: NAME="lint"
      script:
        - yarn lint
    - env: NAME="test"
      script:
        - yarn test
        - yarn e2e
    - env: NAME="test"
      os: osx
      script:
        - yarn test
        - yarn e2e
    - env: NAME="package"
      script:
        - yarn build
        - yarn pack
      after_success:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "application/tar+npm" *.tgz

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/e53cc910-2919-11e8-8bbd-0a580a28060b/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
