name: 'Test'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  job_1:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      # we want that the matrix keeps running, default is to cancel them if it fails.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn e2e
